defmodule WingspanScorer.Repo.Migrations.AddIsWinnerToGamePlayers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_players) do
      add :is_winner, :boolean, default: false
    end
  end

  def down do
    alter table(:game_players) do
      remove :is_winner
    end
  end
end
