defmodule WingspanScorer.Repo.Migrations.AddHummingbirdPoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_players) do
      add :hummingbird_points, :bigint, default: 0
    end
  end

  def down do
    alter table(:game_players) do
      remove :hummingbird_points
    end
  end
end
