defmodule WingspanScorer.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :hashed_password, :text, null: false
      add :name, :text
      add :email, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:games, primary_key: false) do
      add :creator_id,
          references(:users, column: :id, name: "games_creator_id_fkey", type: :uuid),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :completed, :boolean
      add :played_at, :date
      add :expansions, {:array, :text}, default: []
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:game_players, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "game_players_user_id_fkey", type: :uuid)

      add :game_id,
          references(:games, column: :id, name: "game_players_game_id_fkey", type: :uuid),
          null: false

      add :is_winner, :boolean
      add :guest_name, :text
      add :hummingbird_points, :bigint
      add :duet_map_points, :bigint
      add :nectar_wetland, :bigint
      add :nectar_grassland, :bigint
      add :nectar_forest, :bigint
      add :tucked_cards, :bigint
      add :cached_food, :bigint
      add :eggs, :bigint
      add :end_of_round_goals, :bigint
      add :bonus_card_points, :bigint
      add :bird_points, :bigint
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:friendships, primary_key: false) do
      add :friend_id,
          references(:users, column: :id, name: "friendships_friend_id_fkey", type: :uuid),
          null: false

      add :user_id,
          references(:users, column: :id, name: "friendships_user_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:friendships, [:user_id, :friend_id],
             name: "friendships_unique_friendship_index"
           )
  end

  def down do
    drop_if_exists unique_index(:friendships, [:user_id, :friend_id],
                     name: "friendships_unique_friendship_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `friendships` table without the `friendships_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `friendships` table without the `friendships_friend_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:friendships)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `game_players` table without the `game_players_game_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `game_players` table without the `game_players_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:game_players)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `games` table without the `games_creator_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:games)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end