defmodule WingspanScorer.Repo.Migrations.CreateGamesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:games, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :expansions, {:array, :text}, default: []
      add :played_at, :date
      add :completed, :boolean, default: false

      add :creator_id,
          references(:users,
            column: :id,
            name: "games_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:game_players, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bird_points, :bigint, default: 0
      add :bonus_card_points, :bigint, default: 0
      add :end_of_round_goals, :bigint, default: 0
      add :eggs, :bigint, default: 0
      add :cached_food, :bigint, default: 0
      add :tucked_cards, :bigint, default: 0
      add :nectar_forest, :bigint, default: 0
      add :nectar_grassland, :bigint, default: 0
      add :nectar_wetland, :bigint, default: 0
      add :duet_map_points, :bigint, default: 0
      add :guest_name, :text

      add :game_id,
          references(:games,
            column: :id,
            name: "game_players_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "game_players_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_players, "game_players_game_id_fkey")

    drop constraint(:game_players, "game_players_user_id_fkey")

    drop table(:game_players)

    drop constraint(:games, "games_creator_id_fkey")

    drop table(:games)
  end
end
